name: Build Godot Project

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened]

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
        - name: linux
          extension: 
        - name : windows
          extension: .exe
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.5.0
        with:
          name: reno${{ matrix.platform.extension }}
          preset: ${{ matrix.platform.name }}
          debugMode: "true"
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: TohoReno-${{ matrix.platform.name }}
          path: |
            ${{ github.workspace }}/${{ steps.build.outputs.build }}
      - name: Upload Example Config Artifact
        uses: actions/upload-artifact@v2
        with:
          name: TohoReno-${{ matrix.platform.name }}
          path: |
            ${{ github.workspace }}/example-config.cfg