name: Build Godot Project

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.5.0
        with:
          name: example
          preset: ${{ matrix.platform }}
          debugMode: "true"
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: TohoReno-${{ matrix.platform }}
          path: |
            ${{ github.workspace }}/${{ steps.build.outputs.build }}
      - name: Upload Example Config Artifact
        uses: actions/upload-artifact@v2
        with:
          name: TohoReno-${{ matrix.platform }}
          path: |
            ${{ github.workspace }}/example-config.cfg